//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22_TranDuyVu_2210900138.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int ReviewID { get; set; }
        public Nullable<int> GameID { get; set; }
        public string AdminID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public string NoiDungDanhGia { get; set; }
        public Nullable<byte> DanhGia { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual QUAN_TRI QUAN_TRI { get; set; }
        public virtual Game Game { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
