//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22_TranDuyVu_2210900138.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.DANH_GIA = new HashSet<DANH_GIA>();
        }
    
        public int GameID { get; set; }
        public string Ten { get; set; }
        public string TheLoai { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public string NhaPhatTrien { get; set; }
        public Nullable<byte> DanhGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
    }
}
